version: '3.1'


services:
  lokals-master:
    build: ./Lokals
    ports: 
        - "9090:80"
    volumes:
        - ./Lokals/lokals-master:/var/www/html/
    links:
        - db
    networks:
      net:
        ipv4_address: 170.2.0.6 


  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password 
    ports: 
       - "9999:3306"
    environment:
      MYSQL_DATABASE: Lokals
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    volumes:
      # - ./db:/database
      - datafiles:/var/lib/mysql
      - ./Lokals/Tables_Lokals.sql:/docker-entrypoint-initdb.d/populate_db.sql            
    networks:
      net:
        ipv4_address: 170.2.0.2
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '9099:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
    networks:
      net:
        ipv4_address: 170.2.0.3
  
  flask:
    build: ./Lokals/auth_server
    container_name: flasky
    ports:
      - "5001:5001"
    restart:
      always
    environment:
      - FLASK_APP=server
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 170.2.0.4


volumes:
  datafiles:

networks:
  net:
    ipam:
      driver: default
      config:
      - subnet: 170.2.0.0/16
